#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Make 3D mesh in slab of cells.
#cd cylinder_snappyHexMesh
#runApplication blockMesh
#runApplication snappyHexMesh -overwrite

# Make a 2D mesh by extruding a patch and solve to steady state.
#cd ../cylinder2D_pimpleFoam
runApplication extrudeMesh
runApplication createPatch -overwrite
cp -r 0.org 0
runApplication decomposePar
runParallel `getApplication` 8
runApplication reconstructPar
rm -r processor*
# Copy the mesh from the steady state case and map the results to a
# mesh motion case, then solve transient.
#cd ../cylinder2D_pimpleDyMFoam
#cp -r ../cylinder2D_simpleFoam/constant/polyMesh/* constant/polyMesh/
#cp -r 0.org 0
#runApplication mapFields ../cylinder2D_simpleFoam -sourceTime latestTime -consistent
#mv 0/pointDisplacement.unmapped 0/pointDisplacement
#runApplication decomposePar
#runParallel `getApplication` 4
#runApplication reconstructPar

# ----------------------------------------------------------------- end-of-file
