#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Make 3D mesh in slab of cells.
cd cylinder_snappyHexMesh
runApplication blockMesh
runApplication snappyHexMesh -overwrite

# Make a 2D mesh by extruding a patch and solve to steady state.
cd ../cylinder_pimpleFoam
runApplication extrudeMesh
runApplication createPatch -overwrite
cp -r 0.org 0
runApplication decomposePar
runParallel `getApplication` 8
runApplication reconstructPar

cd ../cylinder_Re500
runApplication extrudeMesh
runApplication createPatch -overwrite
cp -r 0.org 0
runApplication decomposePar
runParallel `getApplication` 8
runApplication reconstructPar

cd ../cylinder_Re250
runApplication extrudeMesh
runApplication createPatch -overwrite
cp -r 0.org 0
runApplication decomposePar
runParallel `getApplication` 8
runApplication reconstructPar

# ----------------------------------------------------------------- end-of-file
